# https://docs.github.com/ja/actions/guides/publishing-docker-images
name: Publish Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  PHP_VERSION: 8.4
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          file: ${{ env.PHP_VERSION }}/swoole/Dockerfile
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/${{ env.PHP_VERSION }}-swoole:latest
            docker.pkg.github.com/${{ github.repository }}/${{ env.PHP_VERSION }}-swoole:${{ github.sha }}
