# https://docs.github.com/ja/actions/guides/publishing-docker-images
name: Publish Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build container image: swoole"
        uses: docker/build-push-action@v2
        with:
          file: 8.2/swoole/Dockerfile
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/8.2-swoole:latest
            docker.pkg.github.com/${{ github.repository }}/8.2-swoole:${{ github.sha }}
      - name: "Build container image: swoole-dev"
        uses: docker/build-push-action@v2
        with:
          file: 8.2/swoole/Dockerfile.dev
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/8.2-swoole-dev:latest
            docker.pkg.github.com/${{ github.repository }}/8.2-swoole-dev:${{ github.sha }}
